name: 'Prepare config files for jupyterbook execution'

inputs:
  python-version:
    type: string
    required: true

outputs:
  tutorial-slug:
    description: "Tutorial slug"
    value: ${{ steps.py-yml.outputs.TUTORIAL-SLUG }}

runs:
  using: "composite"
  steps:
    - name: Check out helper scripts from astropy-tutorials
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Add submodule
      run: git submodule add https://github.com/astropy-learn/astropy-tutorials
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build requirements
      shell: bash
      run: pip install pyyaml
    
    - name: Populate _config.yml
      id: py-yml
      shell: bash
      run: echo "TUTORIAL-SLUG=$(python astropy-tutorials/scripts/pre-process.py)" >> "$GITHUB_OUTPUT"